
 # Generated by Django 3.1 on 2020-08-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

     initial = True

     dependencies = [
     ]

     operations = [
         migrations.CreateModel(
             name='Period',
             fields=[
                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                 ('mood', models.CharField(choices=[('1', 'Glücklich'), ('2', 'Krank'), ('3', 'Wütend'), ('4', 'Müde'), ('5', 'Hungrig')], default='3', max_length=50)),
                 ('pain', models.CharField(choices=[('1', 'leicht'), ('2', 'regulär'), ('3', 'stark')], default='2', max_length=50)),
             ],
         ),
     ]