# Generated by Django 3.1 on 2020-08-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='comment',
            field=models.CharField(default='', max_length=251),
        ),
        migrations.AddField(
            model_name='period',
            name='ending_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='starting_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='mood',
            field=models.CharField(choices=[('Glücklich', 'Glücklich'), ('Krank', 'Krank'), ('Wütend', 'Wütend'), ('Müde', 'Müde'), ('Hungrig', 'Hungrig')], default='3', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='pain',
            field=models.CharField(choices=[('keine', 'keine'), ('leicht', 'leicht'), ('regulär', 'regulär'), ('stark', 'stark')], default='2', max_length=51),
        ),
    ]
