# Generated by Django 3.1 on 2020-08-19 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='comnt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='period',
            name='ending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='starting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
