# Generated by Django 3.1 on 2020-08-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0002_auto_20200830_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='comment',
            field=models.CharField(default='', max_length=251, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='pain',
            field=models.CharField(choices=[('keine', 'keine'), ('leicht', 'leicht'), ('regulär', 'regulär'), ('stark', 'stark')], default='2', max_length=51, null=True),
        ),
    ]
