# Generated by Django 3.1 on 2020-08-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0002_auto_20200819_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='comnt',
        ),
    ]
