# Generated by Django 3.1 on 2020-08-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0003_remove_period_comnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='comment',
            field=models.CharField(default='', max_length=250),
        ),
    ]
