# Generated by Django 3.1 on 2020-08-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0004_period_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='ending_date',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='period',
            name='mood',
            field=models.CharField(choices=[('Glücklich', 'Glücklich'), ('Krank', 'Krank'), ('Wütend', 'Wütend'), ('Müde', 'Müde'), ('Hungrig', 'Hungrig')], default='3', max_length=50),
        ),
        migrations.AlterField(
            model_name='period',
            name='pain',
            field=models.CharField(choices=[('leicht', 'leicht'), ('regulär', 'regulär'), ('stark', 'stark')], default='2', max_length=50),
        ),
    ]
