# Generated by Django 3.1 on 2020-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0005_auto_20200821_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='ending_date',
            field=models.CharField(default='noch nicht bekannt', max_length=250),
        ),
        migrations.AlterField(
            model_name='period',
            name='pain',
            field=models.CharField(choices=[('keine', 'keine'), ('leicht', 'leicht'), ('regulär', 'regulär'), ('stark', 'stark')], default='2', max_length=50),
        ),
    ]
