# Generated by Django 3.1 on 2020-08-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0005_auto_20200830_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='ending_date',
        ),
    ]
