# Generated by Django 3.1 on 2020-08-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0006_auto_20200828_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='starting_date',
            field=models.DateField(),
        ),
    ]
