# Generated by Django 3.1 on 2020-08-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0009_auto_20200830_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='ending_date',
            field=models.DateField(null=True),
        ),
    ]
