# Generated by Django 3.1 on 2020-08-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0010_auto_20200829_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='ending_date',
            field=models.DateField(null=True),
        ),
    ]
