# Generated by Django 3.1 on 2020-08-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0011_auto_20200829_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='comment',
            field=models.CharField(default='', max_length=251),
        ),
    ]
