# Generated by Django 3.1.1 on 2020-09-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0012_auto_20200908_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
