# Generated by Django 3.1 on 2020-08-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0012_auto_20200830_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
