# Generated by Django 3.1.1 on 2020-09-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodtracker', '0013_auto_20200909_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
